//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.ISS7
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Оборудование.
    /// </summary>
    // *** Start programmer edit section *** (Оборудование CustomAttributes)

    // *** End programmer edit section *** (Оборудование CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОборудованиеE", new string[] {
            "ИнвНомре as \'Инв номре\'",
            "Название as \'Название\'",
            "Пользователь as \'Пользователь\'",
            "Пользователь.ФИО as \'ФИО\'",
            "Тип as \'Тип\'",
            "Тип.Название as \'Название\'"}, Hidden=new string[] {
            "Пользователь.ФИО",
            "Тип.Название"})]
    [MasterViewDefineAttribute("ОборудованиеE", "Пользователь", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [MasterViewDefineAttribute("ОборудованиеE", "Тип", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Название")]
    public class Оборудование : ICSSoft.STORMNET.DataObject
    {
        
        private string fИнвНомре;
        
        private string fНазвание;
        
        private IIS.ISS7.Пользователь fПользователь;
        
        private IIS.ISS7.Тип fТип;
        
        private IIS.ISS7.РабочееМесто fРабочееМесто;
        
        // *** Start programmer edit section *** (Оборудование CustomMembers)

        // *** End programmer edit section *** (Оборудование CustomMembers)

        
        /// <summary>
        /// ИнвНомре.
        /// </summary>
        // *** Start programmer edit section *** (Оборудование.ИнвНомре CustomAttributes)

        // *** End programmer edit section *** (Оборудование.ИнвНомре CustomAttributes)
        [StrLen(255)]
        public virtual string ИнвНомре
        {
            get
            {
                // *** Start programmer edit section *** (Оборудование.ИнвНомре Get start)

                // *** End programmer edit section *** (Оборудование.ИнвНомре Get start)
                string result = this.fИнвНомре;
                // *** Start programmer edit section *** (Оборудование.ИнвНомре Get end)

                // *** End programmer edit section *** (Оборудование.ИнвНомре Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оборудование.ИнвНомре Set start)

                // *** End programmer edit section *** (Оборудование.ИнвНомре Set start)
                this.fИнвНомре = value;
                // *** Start programmer edit section *** (Оборудование.ИнвНомре Set end)

                // *** End programmer edit section *** (Оборудование.ИнвНомре Set end)
            }
        }
        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (Оборудование.Название CustomAttributes)

        // *** End programmer edit section *** (Оборудование.Название CustomAttributes)
        [StrLen(255)]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (Оборудование.Название Get start)

                // *** End programmer edit section *** (Оборудование.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (Оборудование.Название Get end)

                // *** End programmer edit section *** (Оборудование.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оборудование.Название Set start)

                // *** End programmer edit section *** (Оборудование.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (Оборудование.Название Set end)

                // *** End programmer edit section *** (Оборудование.Название Set end)
            }
        }
        
        /// <summary>
        /// Оборудование.
        /// </summary>
        // *** Start programmer edit section *** (Оборудование.Пользователь CustomAttributes)

        // *** End programmer edit section *** (Оборудование.Пользователь CustomAttributes)
        [NotNull()]
        public virtual IIS.ISS7.Пользователь Пользователь
        {
            get
            {
                // *** Start programmer edit section *** (Оборудование.Пользователь Get start)

                // *** End programmer edit section *** (Оборудование.Пользователь Get start)
                IIS.ISS7.Пользователь result = this.fПользователь;
                // *** Start programmer edit section *** (Оборудование.Пользователь Get end)

                // *** End programmer edit section *** (Оборудование.Пользователь Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оборудование.Пользователь Set start)

                // *** End programmer edit section *** (Оборудование.Пользователь Set start)
                this.fПользователь = value;
                // *** Start programmer edit section *** (Оборудование.Пользователь Set end)

                // *** End programmer edit section *** (Оборудование.Пользователь Set end)
            }
        }
        
        /// <summary>
        /// Оборудование.
        /// </summary>
        // *** Start programmer edit section *** (Оборудование.Тип CustomAttributes)

        // *** End programmer edit section *** (Оборудование.Тип CustomAttributes)
        [NotNull()]
        public virtual IIS.ISS7.Тип Тип
        {
            get
            {
                // *** Start programmer edit section *** (Оборудование.Тип Get start)

                // *** End programmer edit section *** (Оборудование.Тип Get start)
                IIS.ISS7.Тип result = this.fТип;
                // *** Start programmer edit section *** (Оборудование.Тип Get end)

                // *** End programmer edit section *** (Оборудование.Тип Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оборудование.Тип Set start)

                // *** End programmer edit section *** (Оборудование.Тип Set start)
                this.fТип = value;
                // *** Start programmer edit section *** (Оборудование.Тип Set end)

                // *** End programmer edit section *** (Оборудование.Тип Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.ISS7.РабочееМесто.
        /// </summary>
        // *** Start programmer edit section *** (Оборудование.РабочееМесто CustomAttributes)

        // *** End programmer edit section *** (Оборудование.РабочееМесто CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.ISS7.РабочееМесто РабочееМесто
        {
            get
            {
                // *** Start programmer edit section *** (Оборудование.РабочееМесто Get start)

                // *** End programmer edit section *** (Оборудование.РабочееМесто Get start)
                IIS.ISS7.РабочееМесто result = this.fРабочееМесто;
                // *** Start programmer edit section *** (Оборудование.РабочееМесто Get end)

                // *** End programmer edit section *** (Оборудование.РабочееМесто Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оборудование.РабочееМесто Set start)

                // *** End programmer edit section *** (Оборудование.РабочееМесто Set start)
                this.fРабочееМесто = value;
                // *** Start programmer edit section *** (Оборудование.РабочееМесто Set end)

                // *** End programmer edit section *** (Оборудование.РабочееМесто Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОборудованиеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОборудованиеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОборудованиеE", typeof(IIS.ISS7.Оборудование));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Оборудование.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfОборудование CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfОборудование CustomAttributes)
    public class DetailArrayOfОборудование : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.ISS7.DetailArrayOfОборудование members)

        // *** End programmer edit section *** (IIS.ISS7.DetailArrayOfОборудование members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Оборудование by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Оборудование.
        /// </summary>
        public DetailArrayOfОборудование(IIS.ISS7.РабочееМесто fРабочееМесто) : 
                base(typeof(Оборудование), ((ICSSoft.STORMNET.DataObject)(fРабочееМесто)))
        {
        }
        
        public IIS.ISS7.Оборудование this[int index]
        {
            get
            {
                return ((IIS.ISS7.Оборудование)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.ISS7.Оборудование dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
